const languages = {
  "Auto-detect": "auto-detect",
  Afrikaans: "af",
  Amharic: "am",
  Arabic: "ar",
  Assamese: "as",
  Azerbaijani: "az",
  Bulgarian: "bg",
  Bangla: "bn",
  Bosnian: "bs",
  Catalan: "ca",
  Czech: "cs",
  Welsh: "cy",
  Danish: "da",
  German: "de",
  Greek: "el",
  English: "en",
  Spanish: "es",
  Estonian: "et",
  Persian: "fa",
  Finnish: "fi",
  Filipino: "fil",
  Fijian: "fj",
  French: "fr",
  "French (Canada)": "fr-CA",
  Irish: "ga",
  Gujarati: "gu",
  Hebrew: "he",
  Hindi: "hi",
  Croatian: "hr",
  "Haitian Creole": "ht",
  Hungarian: "hu",
  Armenian: "hy",
  Indonesian: "id",
  Icelandic: "is",
  Italian: "it",
  Inuktitut: "iu",
  Japanese: "ja",
  Kazakh: "kk",
  Khmer: "km",
  "Kurdish (Northern)": "kmr",
  Kannada: "kn",
  Korean: "ko",
  "Kurdish (Central)": "ku",
  Lao: "lo",
  Lithuanian: "lt",
  Latvian: "lv",
  Malagasy: "mg",
  Maori: "mi",
  Malayalam: "ml",
  Marathi: "mr",
  Malay: "ms",
  Maltese: "mt",
  "Hmong Daw": "mww",
  Myanmar: "my",
  Norwegian: "nb",
  Nepali: "ne",
  Dutch: "nl",
  Odia: "or",
  "Querétaro Otomi": "otq",
  Punjabi: "pa",
  Polish: "pl",
  Dari: "prs",
  Pashto: "ps",
  "Portuguese (Brazil)": "pt",
  "Portuguese (Portugal)": "pt-PT",
  Romanian: "ro",
  Russian: "ru",
  Slovak: "sk",
  Slovenian: "sl",
  Samoan: "sm",
  Albanian: "sq",
  "Serbian (Cyrillic)": "sr-Cyrl",
  "Serbian (Latin)": "sr-Latn",
  Swedish: "sv",
  Swahili: "sw",
  Tamil: "ta",
  Telugu: "te",
  Thai: "th",
  Tigrinya: "ti",
  "Klingon (Latin)": "tlh-Latn",
  "Klingon (pIqaD)": "tlh-Piqd",
  Tongan: "to",
  Turkish: "tr",
  Tahitian: "ty",
  Ukrainian: "uk",
  Urdu: "ur",
  Vietnamese: "vi",
  "Yucatec Maya": "yua",
  "Cantonese (Traditional)": "yue",
  "Chinese Simplified": "zh-Hans",
  "Chinese Traditional": "zh-Hant",
};
